### ISSUE TITLE
Bug in `rdirmultinom`

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [timjmiller/wham#53] opened 2022-01-03 22:51 UTC
I'm exploring a cross-test of the DirMult and a new distribution for self-weighting comps.  I'm starting with a self-test of the DirMult, and initially got weird results.  I think the reason is a bug in the `rdirmultinom` function, which should simulate a single draw from the Dirichlet for all samples from the multinomial, not a separate draw for each sample.  

Do you want me to do a PR on the main or devel branch, or perhaps have some further discussion here first?

**Comment by timjmiller** [comment] 2022-01-04 14:06
This is a duplicate of [#49](https://github.com/timjmiller/wham/issues/49#issue-992498714). It has been corrected on devel branch.

**Closed** 2022-01-04 14:07 UTC
